### ISSUE TITLE
建议先判断下en_US

### ISSUE THREAD

**Issue by meidea** [vueComponent/vue-cli-plugin-ant-design#1]
https://github.com/vueComponent/vue-cli-plugin-ant-design/blob/915ce1cc7309ccdcf2af46cd8da900006fab96f6/generator/templates/src/plugins/ant-design-vue.js#L15

**Comment by garfield02** [comment]
什么时候能实现可伸缩列？

**Comment by mablevi** [comment]
Running completion hooks...error: Identifier 'zh_CN' is not in camel case (camelcase)

**Comment by wangxueliang** [comment]
ref #10
