### ISSUE TITLE
Which version to install?

### ISSUE THREAD

**Issue by m-thomson** [vueComponent/vue-cli-plugin-ant-design#4]
Hi,

Just so you know, there are three different versions of this that show up in Vue ui:

<img width="670" alt="CleanShot 2019-10-01 at 12 21 56@2x" src="https://user-images.githubusercontent.com/5273016/65993512-418b4280-e446-11e9-8119-f1eac32c9c05.png">

It's very confusing, especially since "vue-cli-plugin-antv" has a higher version number and appears to have updated/newer docs. 

I'm not sure how a repo gets added to the search but if **this repo** is the [correct version](https://github.com/wangxueliang/vue-cli-plugin-antv/issues/1)  can you remove the others from showing up in the search? Thanks!

**Comment by wangxueliang** [comment]
![image](https://user-images.githubusercontent.com/4122593/66262381-c7293c80-e810-11e9-83db-3414f9763973.png)
